export const SITE = {
  company: "Sri Bhairaveshwara Power Control",
  shortName: "SBPC",
  tagline: "Powering Industries with Reliable Electrical Control Solutions",
  proprietor: "Sri Lakshmi",
  phone1: "9986418219",
  phone2: "8050807876",
  phone1Display: "+91 99864 18219",
  phone2Display: "+91 80508 07876",
  email: "sribhairaveshwarapowercontrol@gmail.com",
  whatsapp: "919986418219",
  whatsappMsg: "Hello! I'm interested in your electrical control panels. Please help me with a quote.",
  address: "#127, No. 161,162,163, 3rd Cross, SRY Layout,\nVadarapalya Koppa Road, Mysandra, Begur,\nBangalore - 560068",
  addressOneLine: "#127, No. 161,162,163, 3rd Cross, SRY Layout, Vadarapalya Koppa Road, Mysandra, Begur, Bangalore - 560068",
};

export const PRODUCTS = [
  {
    slug: "apfc-panel",
    name: "APFC Panel",
    icon: "⚡",
    category: "Power Quality",
    tagline: "Automatic Power Factor Correction Panels",
    description: "Our APFC Panels automatically correct power factor to near unity, drastically reducing your electricity bills and improving overall power quality. Designed for industries with varying loads, each panel features a microcontroller-based intelligent controller with real-time PF monitoring.",
    features: [
      "Automatic PF correction to near unity",
      "Microcontroller-based intelligent controller",
      "Capacitor bank switching (fixed & variable)",
      "Harmonic filtration options available",
      "Over-voltage & over-current protection",
      "LED/LCD digital display with data logging",
    ],
    applications: ["Manufacturing Plants", "Commercial Buildings", "Hospitals", "Data Centers"],
    standards: ["IS 13925", "IEC 60831"],
    color: "#1565C0",
  },
  {
    slug: "as-panels",
    name: "Auto Synchronizing Panels",
    icon: "🔄",
    category: "Automation",
    tagline: "Seamless Generator Synchronization",
    description: "Auto Synchronizing Panels ensure the parallel operation of multiple generators or between a generator and the grid, providing seamless load sharing and power transfer. Eliminates manual intervention and ensures uninterrupted power supply.",
    features: [
      "Automatic synchronization with precision timing",
      "Load sharing & load shedding control",
      "Frequency matching algorithms",
      "Voltage & phase angle matching",
      "Manual override with safety interlock",
      "Digital display with event logging",
    ],
    applications: ["Power Plants", "Industrial Facilities", "Hospitals", "Hotels"],
    standards: ["IS 8623", "IEC 61439"],
    color: "#0277BD",
  },
  {
    slug: "mcc-panels",
    name: "MCC Panels",
    icon: "🏭",
    category: "Motor Control",
    tagline: "Motor Control Centers for Industry",
    description: "Motor Control Centers (MCC) are the backbone of industrial motor control. We manufacture fixed, semi draw-out and fully draw-out type MCCs designed for demanding process plants with full compliance to IS 8623 and IEC 61439 standards.",
    features: [
      "Fixed, semi draw-out & draw-out type",
      "DOL, Star-Delta & Soft-Starter options",
      "VFD integration ready",
      "IP54/IP55 protection rating",
      "Comprehensive interlocking facilities",
      "Cable entry from top & bottom",
    ],
    applications: ["Water Treatment Plants", "Chemical Plants", "Steel Plants", "Paper Mills"],
    standards: ["IS 8623", "IEC 61439-2"],
    color: "#00695C",
  },
  {
    slug: "pcc-panel",
    name: "PCC Panel",
    icon: "⚡",
    category: "Power Distribution",
    tagline: "Power Control Centers",
    description: "Power Control Centers (PCC) receive and distribute power from transformers or generators to various sub-distribution boards. Our PCCs are engineered for maximum reliability with ease of maintenance access and future expandability.",
    features: [
      "Incoming & outgoing feeders with ACB/MCCB",
      "Segregated bus bar chambers",
      "Energy metering & power monitoring",
      "Numerical protection relays",
      "Dual power supply (mains + DG) capability",
      "Remote monitoring interface",
    ],
    applications: ["Industrial Plants", "Utility Substations", "Commercial Complexes", "Infrastructure"],
    standards: ["IS 8623", "IEC 61439"],
    color: "#4527A0",
  },
  {
    slug: "amf-panel",
    name: "AMF Panel",
    icon: "🔋",
    category: "Automation",
    tagline: "Automatic Mains Failure Panels",
    description: "AMF Panels automatically detect mains power failure, start the standby generator, and transfer the load — then reverse the process when mains power is restored. Ensuring zero-interruption power supply for critical loads.",
    features: [
      "Auto mains failure detection (< 2 sec)",
      "Automatic DG start & stop sequencing",
      "ATS (Automatic Transfer Switch) control",
      "Adjustable time delays for all sequences",
      "Comprehensive alarm & fault indication",
      "Auto/Manual/Test operating modes",
    ],
    applications: ["Hospitals", "Data Centers", "Commercial Buildings", "Industrial Plants"],
    standards: ["IS 8623", "IEC 60947"],
    color: "#E65100",
  },
  {
    slug: "pd-boards",
    name: "Power Distribution Boards",
    icon: "📋",
    category: "Power Distribution",
    tagline: "LT Power Distribution Boards",
    description: "LT Power Distribution Boards (PDB) distribute electrical power from a single incoming source to multiple outgoing feeders. Built with quality MCBs/MCCBs, proper earthing and protection for safe and reliable distribution.",
    features: [
      "MCB/MCCB outgoing feeders",
      "Aluminium/Copper busbar system",
      "Phase indication lamps",
      "Earth leakage protection (ELCB/RCCB)",
      "Energy metering provisions",
      "IP42 to IP65 protection rating",
    ],
    applications: ["Factories", "Commercial Buildings", "Hotels", "Infrastructure Projects"],
    standards: ["IS 8623", "IEC 61439"],
    color: "#1B5E20",
  },
  {
    slug: "bus-ducts",
    name: "Bus Ducts & Others",
    icon: "🔌",
    category: "Power Distribution",
    tagline: "Compact High-Current Conductors",
    description: "Bus duct systems provide a safe, efficient way to transmit large amounts of electrical power with minimal losses. Our sandwich bus ducts and segregated phase bus ducts are ideal for connecting transformers to switchboards.",
    features: [
      "Sandwich & segregated phase bus duct",
      "Current ratings up to 6300A",
      "Very low impedance & energy loss",
      "Compact, space-saving design",
      "IP54 weather protection",
      "Easy joint & expansion provisions",
    ],
    applications: ["Transformer HV/LV terminations", "Generator connections", "Switchgear interconnections"],
    standards: ["IS 8084", "IEC 61439"],
    color: "#880E4F",
  },
  {
    slug: "lt-metering",
    name: "LT Metering Panel",
    icon: "📊",
    category: "Metering",
    tagline: "Accurate Energy Monitoring",
    description: "LT Metering Panels provide accurate energy measurement and monitoring for billing, audit and power management applications. Complete with CT/PT units, revenue-grade energy meters and communication interfaces for remote monitoring.",
    features: [
      "Revenue-grade CT/PT metering",
      "Multi-function energy meters",
      "Power quality analyzers",
      "Data logging & trending",
      "RS485/Modbus communication",
      "SCADA/BMS integration ready",
    ],
    applications: ["Industrial Plants", "Utility Applications", "Building Management", "Energy Auditing"],
    standards: ["IS 722", "IEC 62053"],
    color: "#F57F17",
  },
  {
    slug: "feeder-pillar",
    name: "Feeder Pillar Panels",
    icon: "🗼",
    category: "Power Distribution",
    tagline: "Outdoor Electrical Distribution",
    description: "Feeder Pillar Panels are weatherproof enclosures for outdoor electrical distribution points. Used for street lighting, landscaping, construction sites and outdoor power distribution, with heavy-duty anti-corrosion coating.",
    features: [
      "IP65 weatherproof enclosure",
      "Heavy-duty powder-coated steel",
      "MCB/MCCB outgoing feeders",
      "Padlock & anti-tamper provisions",
      "Anti-corrosion coating treatment",
      "Stainless steel hardware & hinges",
    ],
    applications: ["Street Lighting", "Landscaping Projects", "Outdoor Events", "Construction Sites"],
    standards: ["IS 8623", "IEC 60439"],
    color: "#37474F",
  },
  {
    slug: "e-house",
    name: "E-House",
    icon: "🏠",
    category: "Specialized",
    tagline: "Modular Prefabricated Electrical Houses",
    description: "E-House (Electrical House) is a complete prefabricated solution housing all electrical equipment — MCC, PCC, transformers, UPS, control systems — in a weatherproof modular structure. Ideal for remote locations and fast deployment.",
    features: [
      "Complete pre-engineered, factory-tested solution",
      "MCC, PCC, transformer & UPS integration",
      "HVAC system for climate control",
      "Fire suppression & detection system",
      "Cable management & trays pre-installed",
      "Quick site deployment — plug & play",
    ],
    applications: ["Oil & Gas Facilities", "Mining Operations", "Remote Power Plants", "Infrastructure Projects"],
    standards: ["IEC 62271", "IS 14165"],
    color: "#3E2723",
  },
];

export const WHY_US = [
  { icon: "🛡️", title: "Engineering-First", desc: "In-house design engineering with rigorous quality review at every stage of manufacturing." },
  { icon: "🏆", title: "Certified Quality", desc: "Panels built to IS/IEC standards with routine test reports and type test certification." },
  { icon: "⏱️", title: "On-Time Delivery", desc: "Streamlined production planning ensures your panels are delivered on schedule, every time." },
  { icon: "🔧", title: "Lifetime Support", desc: "Dedicated service team for AMC, breakdown support, upgrades and spare parts supply." },
  { icon: "⚡", title: "Custom Solutions", desc: "Tailored panel designs to meet your exact specifications and industry requirements." },
  { icon: "🏭", title: "Complete In-House", desc: "Design, fabrication, wiring, testing and commissioning — all under one roof in Bangalore." },
];

export const STATS = [
  { value: "20+", label: "Years of Excellence" },
  { value: "500+", label: "Panels Delivered" },
  { value: "200+", label: "Clients Served" },
  { value: "24/7", label: "Support Available" },
];

export const CERTIFICATIONS = [
  "ISO 9001:2015",
  "BIS Certified",
  "CPRI Tested",
  "IS 8623 Compliant",
  "IEC 61439 Standards",
];
